name: jotrockenmitlocken
description: "Find out sth. interesting about me."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  jotrockenmitlockenrepo:
    path: ../jotrockenmitlockenrepo
  path_provider: ^2.1.2
  url_launcher: ^6.1.8
  go_router: ^13.2.0
  markdown: ^7.2.1
  flutter_markdown: ^0.6.21
  flutter_math_fork: ^0.7.2
  flutter_highlighter: ^0.1.1
  provider: ^6.1.1
  csv: ^5.1.1
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_charts: ^24.2.6
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  mockito: ^5.4.4
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/barbell.png"
  min_sdk_android: 21 
  web:
    generate: true

  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Bewerbungsbilder/
    - assets/images/aiBlog/
    - assets/documents/
    - assets/documents/footer/
    - assets/documents/blog/
    - assets/data/

fonts:
    - family: Montserrat
      fonts:
        - asset: static/Montserrat-Thin.ttf
        - asset: static/Montserrat-ExtraLight.ttf
        - asset: static/Montserrat-Light.ttf
        - asset: static/Montserrat-Regular.ttf
        - asset: static/Montserrat-Medium.ttf
        - asset: static/Montserrat-SemiBold.ttf
        - asset: static/Montserrat-Bold.ttf
        - asset: static/Montserrat-ExtraBold.ttf
        - asset: static/Montserrat-Black.ttf
        - asset: static/Montserrat-ThinItalic.ttf
          style: italic
        - asset: static/Montserrat-ExtraLightItalic.ttf
          style: italic
        - asset: static/Montserrat-LightItalic.ttf
          style: italic
        - asset: static/Montserrat-Italic.ttf
          style: italic
        - asset: static/Montserrat-MediumItalic.ttf
          style: italic
        - asset: static/Montserrat-SemiBoldItalic.ttf
          style: italic
        - asset: static/Montserrat-BoldItalic.ttf
          style: italic
        - asset: static/Montserrat-ExtraBoldItalic.ttf
          style: italic
        - asset: static/Montserrat-BlackItalic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: Roboto-Black.ttf
        - asset: Roboto-BlackItalic.ttf
          style: italic
        - asset: Roboto-Bold.ttf
          weight: 700
        - asset: Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: Roboto-Italic.ttf
          style: italic
        - asset: Roboto-Light.ttf
        - asset: Roboto-LightItalic.ttf
          style: italic
        - asset: Roboto-Medium.ttf
          weight: 400
        - asset: Roboto-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: Roboto-Regular.ttf
        - asset: Roboto-Thin.ttf
          weight: 200
        - asset: Roboto-ThinItalic.ttf
          weight: 200
          style: italic
